"""The blob map generator: manifest in, script global out, deterministic."""

import json

from build_blob_map import build_blob_map


def _manifest(tmp_path, items):
    path = tmp_path / "manifest.json"
    path.write_text(json.dumps({"set": "E1", "files": items}), encoding="utf-8")
    return path


def test_map_contains_every_hashed_face(tmp_path):
    manifest = _manifest(
        tmp_path,
        [
            {"file": "Zap.webp", "sha256": "a" * 64},
            {"file": "FLX, Unstoppable Rig.webp", "sha256": "b" * 64},
            {"file": "broken entry without hash"},
        ],
    )
    out = tmp_path / "blob-map.js"
    count = build_blob_map(manifest, out)
    text = out.read_text(encoding="utf-8")
    assert count == 2
    assert text.startswith("/* Generated by scripts/build_blob_map.py")
    assert '"Zap.webp": "' + "a" * 64 + '"' in text
    assert "FLX, Unstoppable Rig.webp" in text
    assert "broken entry" not in text


def test_map_survives_a_bom_and_stays_deterministic(tmp_path):
    items = [{"file": "B.webp", "sha256": "b" * 64}, {"file": "A.webp", "sha256": "a" * 64}]
    path = tmp_path / "manifest.json"
    path.write_bytes(b"\xef\xbb\xbf" + json.dumps({"files": items}).encode("utf-8"))
    out1 = tmp_path / "one.js"
    out2 = tmp_path / "two.js"
    build_blob_map(path, out1)
    build_blob_map(path, out2)
    assert out1.read_text(encoding="utf-8") == out2.read_text(encoding="utf-8")
    text = out1.read_text(encoding="utf-8")
    assert text.index('"A.webp"') < text.index('"B.webp"'), "sorted keys keep the diff stable"
