"""Tests for the playable-data compiler behind the local game."""

import json
from pathlib import Path

from build_play_data import (
    parse_cost,
    parse_keywords,
    parse_ops,
    parse_stats,
    playable_records,
    render_module,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
CARDS = json.loads((REPO_ROOT / "cards" / "e1-cards.json").read_text(encoding="utf-8"))["cards"]
FACE_FILES = {
    item["id"]: item["file"]
    for item in json.loads(
        (REPO_ROOT / "art" / "cards" / "final" / "manifest.json").read_text(encoding="utf-8")
    )["files"]
}


def test_costs_split_into_generic_and_affinity():
    assert parse_cost("") is None
    assert parse_cost("0") == {"generic": 0}
    assert parse_cost("3SS") == {"generic": 3, "S": 2}
    assert parse_cost("P") == {"generic": 0, "P": 1}
    assert parse_cost("2BBBB") == {"generic": 2, "B": 4}


def test_stats_tolerate_blanks_and_variables():
    assert parse_stats("4/4") == (4, 4)
    assert parse_stats("0/3") == (0, 3)
    assert parse_stats("") == (None, None)
    assert parse_stats("*/*") == (None, None)


def test_keywords_the_engine_enforces_are_detected():
    names = lambda text: [k["name"] for k in parse_keywords(text)]  # noqa: E731

    assert "Broadcast" in names("Broadcast")
    assert "First Strike" in names("First Strike (This Avatar deals clash damage before)")
    assert "Firewall" in names("Firewall (This Avatar can't attack.)")
    assert names("Attach to Avatar") == ["Attach"]
    assert parse_keywords("Shielded from Keys")[0] == {"name": "Shielded", "from": "Keys"}
    # Broadcast Guard must not also register a bare Broadcast.
    assert names("Broadcast Guard") == ["Broadcast Guard"]


def test_recurring_ability_templates_compile_to_ops():
    assert parse_ops("generate 1 Power", "X") == [
        {"op": "generate", "amount": 1, "affinity": "Power"}
    ]
    assert parse_ops("generate 2 neutral Resources", "X") == [
        {"op": "generate", "amount": 2, "affinity": "neutral"}
    ]
    assert parse_ops("Zap deals 3 damage to any target", "Zap") == [
        {"op": "damage", "amount": 3, "target": "any"}
    ]
    assert parse_ops("draw a card", "X") == [{"op": "draw", "amount": 1}]
    assert parse_ops("Target Avatar gets +3 Action and +3 Resilience until end of turn", "X") == [
        {
            "op": "pump",
            "target": "target-avatar",
            "action": 3,
            "resilience": 3,
            "duration": "eot",
        }
    ]
    assert parse_ops("Decommission target Resource", "X") == [
        {"op": "decommission", "scope": "target", "kind": "Resource"}
    ]


def test_unrecognised_text_stays_unscripted_for_manual_resolution():
    assert parse_ops("After this turn, take one additional turn", "X") is None
    assert parse_ops("Each player chooses a number of Resources", "X") is None


def test_every_card_compiles_and_keeps_its_face():
    records = playable_records(CARDS, FACE_FILES)

    assert len(records) == 295
    assert all(record["face"] for record in records)
    assert all(record["name"] and record["type"] for record in records)
    # Resources are the only cards allowed to have no printed cost.
    for record in records:
        if record["costParsed"] is None:
            assert "Resource" in record["type"], record["id"]
    scripted = [record for record in records if not record["manual"]]
    assert len(scripted) >= 80, "the recurring templates should cover a solid core"
    assert any(record["abilities"] for record in records)


def test_avatars_expose_playable_stats():
    records = {record["id"]: record for record in playable_records(CARDS, FACE_FILES)}
    flx = records["E1-003"]

    assert flx["type"] == "Avatar"
    assert (flx["action"], flx["resilience"]) == (4, 4)
    assert flx["costParsed"] == {"generic": 3, "S": 2}
    assert "Broadcast" in [k["name"] for k in flx["keywords"]]


def test_module_is_a_plain_script_the_page_can_load():
    module = render_module(playable_records(CARDS, FACE_FILES))

    assert module.startswith("/* Generated by scripts/build_play_data.py")
    # globalThis, not window: identical in a browser, and requireable in node so
    # the referee core can be tested against the real catalog.
    assert "globalThis.E1_CARDS = [" in module
    assert "module.exports = globalThis.E1_CARDS" in module
    assert "</script" not in module


def test_built_game_files_are_committed():
    data = (REPO_ROOT / "site" / "play-data.js").read_text(encoding="utf-8")
    page = (REPO_ROOT / "site" / "play.html").read_text(encoding="utf-8")
    engine = (REPO_ROOT / "site" / "play.js").read_text(encoding="utf-8")

    referee = (REPO_ROOT / "site" / "engine.js").read_text(encoding="utf-8")

    assert "globalThis.E1_CARDS" in data
    assert '<script src="play-data.js">' in page and '<script src="play.js">' in page
    assert '<script src="engine.js">' in page
    assert 'href="rules.html"' in page
    # The framework the referee core promises to enforce. These moved out of
    # play.js into the pure engine when the rules were split from the view.
    for token in ("burnBuffers", "stateChecks", "applyCombatDamage", "First Strike", "Overflow"):
        assert token in referee
    # play.js is now a view and a controller: it must not re-implement rules.
    assert "createGame" in engine and "E1Engine" in engine
