"""Compile cards/e1-blob-manifest.json into site/blob-map.js.

The pages resolve a card face to its Blossom blob by SHA-256; this emits the
face-file -> sha256 map as a plain script global, so play.html and deck.html
keep working from file:// where fetch() of local JSON is blocked.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER = (
    "/* Generated by scripts/build_blob_map.py from cards/e1-blob-manifest.json.\n"
    " * Face file name -> SHA-256. The hash IS the Blossom address. */\n"
)


def build_blob_map(manifest_path: Path, out_path: Path) -> int:
    """Write the face->sha256 map script. Returns the number of entries."""
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    items = next(
        (
            value
            for value in manifest.values()
            if isinstance(value, list) and value and isinstance(value[0], dict)
        ),
        [],
    )
    mapping = {
        entry["file"]: entry["sha256"]
        for entry in items
        if entry.get("file") and entry.get("sha256")
    }
    body = json.dumps(mapping, indent=1, sort_keys=True, ensure_ascii=False)
    out_path.write_text(f"{HEADER}globalThis.E1_BLOBS = {body};\n", encoding="utf-8")
    return len(mapping)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=ROOT / "cards" / "e1-blob-manifest.json")
    parser.add_argument("--out", type=Path, default=ROOT / "site" / "blob-map.js")
    args = parser.parse_args()
    count = build_blob_map(args.manifest, args.out)
    print(f"wrote {args.out} ({count} faces)")


if __name__ == "__main__":
    main()
