"""Render card faces that print the Fast (F1.0) values, for local play-testing.

The published faces (art/cards/node-runner-web, mirrored as Blossom blobs) print
the Classic cost, stats and rules text, so a Fast game showed numbers its
engine does not play. This renders all 295 cards again, through the same
renderer, with the Fast values from cards/e1-fast.json overlaid:

    art/cards/fast-web/<name>.webp   the faces (gitignored: a local test build)
    site/fast-faces.js               which faces exist + where the art sits (gitignored)

The table and the Stack Builder use them for Fast games when site/fast-faces.js
is present, and fall back to the published Classic faces when it is not. Nothing
published moves: no blob hash, manifest or blob map is touched.

    uv run python scripts/build_fast_faces.py            # all 295
    uv run python scripts/build_fast_faces.py --limit 12 # a quick look
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from build_play_data import apply_fast_values

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "art" / "cards" / "fast-web"
MANIFEST = ROOT / "site" / "fast-faces.js"
# The published faces were rendered at 88; the renderer's default of 82 is a trap.
QUALITY = 88


def fast_cards() -> dict:
    """The Classic card file with the Fast values overlaid, same shape as e1-cards.json."""
    classic = json.loads((ROOT / "cards" / "e1-cards.json").read_text(encoding="utf-8"))
    fast = json.loads((ROOT / "cards" / "e1-fast.json").read_text(encoding="utf-8"))
    return dict(classic, cards=apply_fast_values(classic["cards"], fast))


def write_manifest(sidecar: Path, out: Path) -> int:
    """site/fast-faces.js from the renderer's geometry sidecar. Returns the face count."""
    data = json.loads(sidecar.read_text(encoding="utf-8-sig"))
    faces = {f"{name}.webp": entry["art"] for name, entry in data["faces"].items()}
    body = json.dumps({"dir": "../art/cards/fast-web/", "size": data["size"], "faces": faces},
                      indent=1, sort_keys=True, ensure_ascii=False)
    out.write_text(
        "/* Generated by scripts/build_fast_faces.py - local test build, not committed.\n"
        " * Faces printing the Fast values: file name -> [x, y, w, h] of the art. */\n"
        f"globalThis.E1_FAST_FACES = {body};\n",
        encoding="utf-8",
    )
    return len(faces)


def main() -> None:
    """Render the Fast faces and write the manifest the site reads."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=0, help="render only the first N cards")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as tmp:
        cards_path = Path(tmp) / "e1-fast-cards.json"
        cards_path.write_text(json.dumps(fast_cards(), ensure_ascii=False), encoding="utf-8")
        command = [
            sys.executable, str(ROOT / "scripts" / "render_card_pngs.py"),
            "--cards", str(cards_path), "--out", str(OUT), "--format", "webp",
            "--quality", str(QUALITY), "--promos", str(Path(tmp) / "no-promos.json"),
        ]
        if args.limit:
            command += ["--limit", str(args.limit)]
        subprocess.run(command, check=True)
    count = write_manifest(OUT / "face-geometry.json", MANIFEST)
    print(f"wrote {MANIFEST.relative_to(ROOT)} for {count} Fast faces")


if __name__ == "__main__":
    main()
