"""Hash a rendered card set for content-addressed publishing.

Blossom addresses every blob by the SHA-256 of its bytes, so the hash *is* the
identifier: a server serves `GET /<sha256>` and any mirror holding the same bytes
answers identically. Ordinals need the same digest to verify what was inscribed.
This writes one manifest both paths can use, and can emit an `ord` batch file.

Inscription has a hard ceiling that Blossom does not: Bitcoin caps a standard
transaction at 400,000 weight units, and witness bytes cost one unit each, so an
inscription payload must stay under roughly 390 KB. Files above that are reported
and excluded from the batch file rather than failing later at broadcast time.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
INSCRIPTION_LIMIT = 390 * 1024
MIME = {".png": "image/png", ".webp": "image/webp", ".jpg": "image/jpeg"}


def sha256_file(path: Path, chunk: int = 1 << 20) -> str:
    """Hash a file without loading it fully into memory."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while block := handle.read(chunk):
            digest.update(block)
    return digest.hexdigest()


def blob_records(
    directory: Path, cards: list[dict[str, Any]], blossom_base: str | None
) -> list[dict[str, Any]]:
    """Describe every rendered face by content hash, joined back to its card."""
    by_name = {card["name"]: card for card in cards}
    records = []
    for path in sorted(directory.iterdir()):
        if path.suffix.lower() not in MIME:
            continue
        card = by_name.get(path.stem)
        digest = sha256_file(path)
        size = path.stat().st_size
        record: dict[str, Any] = {
            "id": card["id"] if card else None,
            "name": path.stem,
            "file": path.name,
            "mime": MIME[path.suffix.lower()],
            "bytes": size,
            "sha256": digest,
            "inscribable": size <= INSCRIPTION_LIMIT,
        }
        if blossom_base:
            record["blossom"] = f"{blossom_base.rstrip('/')}/{digest}{path.suffix.lower()}"
        records.append(record)
    return records


def render_manifest(records: list[dict[str, Any]], source: Path) -> dict[str, Any]:
    """Wrap the records with the totals a publisher needs before uploading."""
    total = sum(record["bytes"] for record in records)
    oversize = [record["name"] for record in records if not record["inscribable"]]
    return {
        "set": "600B Timelock TCG — Edition One",
        "frame": "Node Runner",
        "source": source.name,
        "count": len(records),
        "total_bytes": total,
        "inscribable_count": len(records) - len(oversize),
        "inscription_limit_bytes": INSCRIPTION_LIMIT,
        "oversize_for_inscription": oversize,
        "files": records,
    }


def render_ord_batch(records: list[dict[str, Any]], source: Path, postage: int) -> str:
    """Emit an `ord wallet batch` file for the entries that fit a standard transaction."""
    lines = [
        "# Generated by scripts/build_blob_manifest.py",
        "# Review fees with `ord wallet batch --dry-run` before broadcasting.",
        "mode: separate-outputs",
        f"postage: {postage}",
        "inscriptions:",
    ]
    for record in records:
        if not record["inscribable"]:
            continue
        path = (source / record["file"]).as_posix()
        lines.append(f'  - file: "{path}"')
        lines.append("    metadata:")
        lines.append(f'      name: "{record["name"]}"')
        if record["id"]:
            lines.append(f'      id: "{record["id"]}"')
        lines.append('      set: "600B Timelock TCG — Edition One"')
        lines.append('      frame: "Node Runner"')
    return "\n".join(lines) + "\n"


def main() -> None:
    """Hash a rendered card directory and write its publishing manifest."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dir", type=Path, default=REPO_ROOT / "art" / "cards" / "node-runner-faces"
    )
    parser.add_argument("--cards", type=Path, default=REPO_ROOT / "cards" / "e1-cards.json")
    parser.add_argument("--out", type=Path, default=None, help="default: <dir>/manifest.json")
    parser.add_argument(
        "--blossom-base",
        default=None,
        help="server base URL, e.g. https://blossom.primal.net",
    )
    parser.add_argument("--ord-batch", type=Path, default=None, help="also write an ord batch file")
    parser.add_argument("--postage", type=int, default=546, help="sats per inscription output")
    args = parser.parse_args()

    if not args.dir.is_dir():
        raise SystemExit(f"no rendered set at {args.dir} — run scripts/render_card_pngs.py first")

    cards = json.loads(args.cards.read_text(encoding="utf-8"))["cards"]
    records = blob_records(args.dir, cards, args.blossom_base)
    if not records:
        raise SystemExit(f"no image files in {args.dir}")

    manifest = render_manifest(records, args.dir)
    out = args.out or args.dir / "manifest.json"
    out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    unmatched = [record["name"] for record in records if record["id"] is None]
    print(f"hashed {manifest['count']} files ({manifest['total_bytes'] / 1024 / 1024:.1f} MB)")
    print(f"wrote {out}")
    if unmatched:
        print(f"note: {len(unmatched)} file(s) matched no card, first: {unmatched[0]}")
    if manifest["oversize_for_inscription"]:
        over = len(manifest["oversize_for_inscription"])
        print(
            f"note: {over} file(s) exceed the ~{INSCRIPTION_LIMIT // 1024} KB "
            "standard-transaction ceiling and cannot be inscribed as-is; "
            "re-render with --format webp for an inscription set"
        )
    if args.ord_batch:
        args.ord_batch.write_text(
            render_ord_batch(records, args.dir, args.postage), encoding="utf-8"
        )
        print(f"wrote {args.ord_batch} with {manifest['inscribable_count']} inscriptions")


if __name__ == "__main__":
    main()
