"""Emit site/face-geometry.js from the renderer's face-geometry sidecar.

The game board shows a card as its pure illustration plus data chips; the full
face appears on inspect. The renderer records where each illustration sits
inside its emitted face image, and this script publishes that map to the site,
keyed exactly like E1_BLOBS in blob-map.js: face file name, extension included.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = (
    "/* Generated by scripts/build_face_geometry.py from the renderer's\n"
    " * face-geometry.json. Face file name -> [x, y, w, h]: where the\n"
    " * illustration sits inside that face image, in its own pixels. */\n"
)


def build_face_geometry(sidecar_path: Path, out_path: Path) -> int:
    """Write the geometry script. Returns the number of entries."""
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8-sig"))
    faces = {f"{name}.webp": entry["art"] for name, entry in sidecar["faces"].items()}
    payload = {"size": sidecar["size"], "faces": faces}
    body = json.dumps(payload, indent=1, sort_keys=True, ensure_ascii=False)
    out_path.write_text(f"{HEADER}globalThis.FACE_GEOMETRY = {body};\n", encoding="utf-8")
    return len(faces)


def main() -> None:
    """CLI wrapper with the repo's canonical paths."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sidecar",
        type=Path,
        default=ROOT / "art" / "cards" / "node-runner-web" / "face-geometry.json",
    )
    parser.add_argument("--out", type=Path, default=ROOT / "site" / "face-geometry.js")
    args = parser.parse_args()
    count = build_face_geometry(args.sidecar, args.out)
    print(f"wrote {args.out} ({count} faces)")


if __name__ == "__main__":
    main()
