"""Build the booster box the shop opens, into site/shop-data.js.

One box, one order, one commitment. `scripts/build_asset_set.py` already
expands the set into physical cards, shuffles with a seeded Fisher-Yates and
publishes the SHA-256 over the ordered box — the promise that nobody reshuffled
after selling. This emits the same box for the browser: compact (card ids, not
records), with the commitment and the seed, so a demo pull behaves exactly the
way a paid pull will and the odds a player sees are the odds the box holds.

Rarity is expressed as copies in the box, exactly as a printed booster box
works: commons are the floor, rares are the reason to open another one.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAY_DATA = ROOT / "site" / "play-data.js"
OUT = ROOT / "site" / "shop-data.js"

# Copies of each card in one demo box, by tier.
#
# These track the MINT's own shape rather than a flat curve, so the free box
# teaches the economy people will meet when they buy rather than contradicting
# it. Share of the whole box, this box against the mint's — over the WHOLE box
# in both columns, Basics counted in, because a percentage that quietly drops a
# fifteenth of the box flatters every remaining row:
#
#   common 66.67% / 66.67   uncommon 19.44% / 20.00   rare 6.67% / 6.19
#   vault   0.39% /  0.42   genesis   0.17% /  0.06   basic 6.67% / 6.67
#
# Genesis sits three times high and cannot be lowered: one copy per card is the
# floor, and matching the mint's 0.06% would need a box of ~14,000 cards this
# page has to download. Said here rather than rounded away on the page.
#
# NOTE the previous comment claimed this was "the same run as the mint's set".
# It was not — the mint runs 6,975/2,511/648/189/63 — and that was one half of the
# two-different-boxes problem a review found on the shop page.
#
# .get()'s default is deliberately absent below: an unknown tier must be a loud
# KeyError at build time, not a card that quietly prints one copy.
PRINT_RUN = {
    "common": 40,
    "uncommon": 14,
    "rare": 4,
    "vault": 1,
    "genesis": 1,
    "basic": 36,
    "promo": 1,
}
# Fifteen, the same pack the mint sells, and 5,400 cards divide into 360 of them
# with nothing left in the bottom of the box.
PACK_SIZE = 15
PRICE_MSAT = 21000  # per card; identical across the box or the pull breaks

HEADER = (
    "/* Generated by scripts/build_shop_data.py - do not edit by hand.\n"
    " * One booster box: the ordered card ids, the seed that shuffled them and\n"
    " * the SHA-256 commitment over that order. Published before selling, so a\n"
    " * pull can be audited instead of trusted. */\n"
)


def load_cards() -> list[dict]:
    """The catalog the game itself plays with, so faces and names agree."""
    text = PLAY_DATA.read_text(encoding="utf-8")
    return json.loads(text[text.index("[") : text.rindex("]") + 1])


def mulberry32(seed: int):
    """The PRNG the card frame and the asset set already use."""
    state = seed & 0xFFFFFFFF

    def next_float() -> float:
        nonlocal state
        state = (state + 0x6D2B79F5) & 0xFFFFFFFF
        t = state
        t = ((t ^ (t >> 15)) * (1 | t)) & 0xFFFFFFFF
        t = (t + (((t ^ (t >> 7)) * (61 | t)) & 0xFFFFFFFF)) & 0xFFFFFFFF
        t ^= t >> 14
        return (t & 0xFFFFFFFF) / 4294967296

    return next_float


def shuffle(items: list[str], seed: int) -> list[str]:
    """Fisher-Yates with a seeded PRNG: auditable from the seed alone."""
    out = list(items)
    rand = mulberry32(seed)
    for i in range(len(out) - 1, 0, -1):
        j = int(rand() * (i + 1))
        out[i], out[j] = out[j], out[i]
    return out


def commitment(box: list[str]) -> str:
    """SHA-256 over the exact ordered box — publish before the first sale."""
    digest = hashlib.sha256()
    for card_id in box:
        digest.update(card_id.encode())
        digest.update(b"\x00")
    return digest.hexdigest()


def build_box(cards: list[dict], seed: int) -> list[str]:
    """Expand to one entry per physical card in catalog order, then shuffle."""
    flat: list[str] = []
    for card in cards:
        flat.extend([card["id"]] * PRINT_RUN[card["rarity"]])
    return shuffle(flat, seed)


def build_shop_data(cards: list[dict], seed: int) -> dict:
    """The whole payload the browser needs to open packs honestly."""
    box = build_box(cards, seed)
    tally: dict[str, int] = {}
    for card in cards:
        rarity = card["rarity"]
        tally[rarity] = tally.get(rarity, 0) + PRINT_RUN[rarity]
    return {
        "set": "E1",
        "seed": seed,
        "packSize": PACK_SIZE,
        "priceMsat": PRICE_MSAT,
        "printRun": PRINT_RUN,
        "boxSize": len(box),
        "odds": {
            rarity: round(100 * count / len(box), 2) for rarity, count in sorted(tally.items())
        },
        "commitment": commitment(box),
        "box": box,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=600, help="box shuffle seed")
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    data = build_shop_data(load_cards(), args.seed)
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    exports = (
        'if (typeof module === "object" && module.exports) module.exports = globalThis.E1_BOX;'
    )
    args.out.write_text(f"{HEADER}globalThis.E1_BOX = {body};\n{exports}\n", encoding="utf-8")

    sats_per_pack = data["priceMsat"] * data["packSize"] // 1000
    print(f"wrote {args.out}")
    print(f"  {data['boxSize']} physical cards, {data['packSize']} per pack")
    print("  odds: " + ", ".join(f"{k} {v}%" for k, v in data["odds"].items()))
    print(f"  price {data['priceMsat']} msat/card -> {sats_per_pack} sats per pack")
    print(f"  PUBLISH BEFORE SELLING — box commitment sha256 = {data['commitment']}")


if __name__ == "__main__":
    main()
