"""Build the preconstructed Stack library into site/precons.js.

Two shelves, both deterministic and fully scripted (no assisted `!` cards, no
Stake module, no X costs), so a first game never needs the manual controls:

- Starters: one mono-affinity Stack per affinity in the engine's own prototype
  shape (17 Resources / 14 Avatars / 5 Zaps+Operations / 4 Hardware+Protocol).
- Classics: the strategy skeletons of the famous early-tournament archetypes —
  burn, weenie swarm, control, ramp, denial, value — rebuilt from original
  600B cards. Shapes vary per archetype; explicit decklists only need the
  engine's floor of 40 and the Stake gate.

Cards are chosen by filters and sorted picks over play-data's compiled ops,
never at random: the same catalog always yields the same library.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAY_DATA = ROOT / "site" / "play-data.js"
OUT = ROOT / "site" / "precons.js"

AFFINITIES = ["Power", "Bitcoin", "Keys", "Signal", "Timelock"]
STAKE = re.compile(r"\bStake\b")

HEADER = (
    "/* Generated by scripts/build_precons.py - do not edit by hand.\n"
    " * Preconstructed Stacks from original 600B cards only: five mono-affinity\n"
    " * Starters in the engine's prototype shape, and the Classics - the old\n"
    " * tournament archetypes rebuilt on this catalog. Fully scripted cards\n"
    " * only, so a first game never touches the manual controls. */\n"
)


def load_cards() -> list[dict]:
    """Read the generated play-data.js and return the raw card list."""
    text = PLAY_DATA.read_text(encoding="utf-8")
    start = text.index("[")
    end = text.rindex("]")
    return json.loads(text[start : end + 1])


def cost_total(card: dict) -> int:
    """Total printed cost, generic plus every symbol."""
    parsed = card.get("costParsed") or {}
    return sum(v for k, v in parsed.items() if k != "x" and isinstance(v, int))


def ops_of(card: dict) -> list[dict]:
    """Every compiled op on the card, across all abilities."""
    out = []
    for ability in card.get("abilities") or []:
        out.extend(ability.get("ops") or [])
    return out


def eligible(card: dict, affinity: str | None) -> bool:
    """Scripted, Stake-free, X-free, and inside the affinity (or Neutral)."""
    if card.get("manual"):
        return False
    if STAKE.search(card.get("text") or ""):
        return False
    if (card.get("costParsed") or {}).get("x") is not None:
        return False
    if affinity is None:
        return True
    aff = card.get("affinity") or []
    return affinity in aff or "Neutral" in aff


def by_curve(cards: list[dict]) -> list[dict]:
    return sorted(cards, key=lambda c: (cost_total(c), c["id"]))


MAX_COPIES = 3
"""Rulebook 7. Mirrors MAX_COPIES in site/engine.js, which is authoritative."""


def _uncapped(card: dict) -> bool:
    """Basic Resources are exempt, exactly as they are in the engine."""
    return card.get("type") == "Basic Resource"


def fill(picks: list[dict], count: int) -> list[str]:
    """Exactly `count` ids: distinct picks first, then copies within the copy limit.

    The rotation used to be unbounded, so a narrow pick list produced four or more
    copies of one Avatar and the referee refused the resulting Stack outright. A
    precon that cannot be played is worse than a slightly worse precon.
    """
    if not picks:
        return []
    out = [c["id"] for c in picks[:count]]
    counts: dict[str, int] = {}
    for card_id in out:
        counts[card_id] = counts.get(card_id, 0) + 1
    i = 0
    guard = 0
    while len(out) < count and guard < count * len(picks) * MAX_COPIES:
        guard += 1
        card_id = picks[i % len(picks)]["id"]
        i += 1
        if counts.get(card_id, 0) >= MAX_COPIES and not _uncapped(picks[(i - 1) % len(picks)]):
            continue
        counts[card_id] = counts.get(card_id, 0) + 1
        out.append(card_id)
    return out


def is_type(card: dict, *types: str) -> bool:
    return card.get("type") in types


def starter(cards: list[dict], affinity: str) -> list[str]:
    """The engine's 17/14/5/4 prototype shape, curated instead of rolled."""
    pool = [c for c in cards if eligible(c, affinity)]
    basics = by_curve(
        [c for c in pool if is_type(c, "Basic Resource") and affinity in c["affinity"]]
    )
    nonbasic = by_curve([c for c in pool if is_type(c, "Resource")])
    avatars = by_curve([c for c in pool if is_type(c, "Avatar", "Hardware Avatar")])
    cheap = [c for c in avatars if cost_total(c) <= 2]
    mid = [c for c in avatars if 3 <= cost_total(c) <= 4]
    top = [c for c in avatars if cost_total(c) >= 5]
    spells = by_curve([c for c in pool if is_type(c, "Zap", "Operation")])
    devices = by_curve([c for c in pool if is_type(c, "Hardware", "Protocol")])
    resources = fill(nonbasic, min(7, len(nonbasic))) + fill(basics, 17 - min(7, len(nonbasic)))
    lineup = fill(cheap or mid, 6) + fill(mid or cheap, 5) + fill(top or mid or cheap, 3)
    return resources + lineup + fill(spells, 5) + fill(devices, 4)


def has_op(card: dict, op_name: str, **wants) -> bool:
    for op in ops_of(card):
        if op.get("op") != op_name:
            continue
        if all(op.get(key) == value for key, value in wants.items()):
            return True
    return False


def action_of(card: dict) -> int:
    return card.get("action") or 0


def resilience_of(card: dict) -> int:
    return card.get("resilience") or 0


def classic(cards: list[dict], spec: dict) -> list[str]:
    """One archetype: resources + scored avatar and spell picks to exact counts."""
    pool = [c for c in cards if eligible(c, spec.get("affinity"))]
    basics = by_curve(
        [c for c in pool if is_type(c, "Basic Resource") and spec["affinity"] in c["affinity"]]
    )
    nonbasic = by_curve([c for c in pool if is_type(c, "Resource")])
    n_nonbasic = min(6, len(nonbasic))
    resources = fill(nonbasic, n_nonbasic) + fill(basics, spec["resources"] - n_nonbasic)

    avatars = [c for c in pool if is_type(c, "Avatar", "Hardware Avatar")]
    avatars = sorted(avatars, key=spec["avatar_key"])
    spells = [c for c in pool if is_type(c, "Zap", "Operation")]
    spells = sorted(spells, key=spec["spell_key"])
    devices = by_curve([c for c in pool if is_type(c, "Hardware", "Protocol")])

    return (
        resources
        + fill(avatars, spec["avatars"])
        + fill(spells, spec["spells"])
        + fill(devices, spec["devices"])
    )


def classics_specs() -> list[dict]:
    """The old lessons, one Stack each. Sort keys are (score desc, curve, id)."""

    def prefer(flag_fn, tiebreak=cost_total):
        return lambda c: (0 if flag_fn(c) else 1, tiebreak(c), c["id"])

    def punch(c):  # action per cost, cheap and violent first
        return (-(action_of(c) - cost_total(c)), cost_total(c), c["id"])

    def wall(c):  # resilience-heavy bodies for the long game
        return (-(resilience_of(c)), cost_total(c), c["id"])

    return [
        {
            "key": "ember",
            "name": "Ember Lesson",
            "affinity": "Power",
            "tagline": "Every point of damage goes upstairs - the oldest tempo-burn lesson.",
            "resources": 16,
            "avatars": 10,
            "spells": 10,
            "devices": 4,
            "avatar_key": punch,
            "spell_key": prefer(
                lambda c: has_op(c, "damage", target="any") or has_op(c, "damage", target="player")
            ),
        },
        {
            "key": "swarm",
            "name": "Relay Swarm",
            "affinity": "Signal",
            "tagline": "Many small friends, all attacking - the weenie swarm, reborn.",
            "resources": 15,
            "avatars": 18,
            "spells": 4,
            "devices": 3,
            "avatar_key": lambda c: (cost_total(c), -action_of(c), c["id"]),
            "spell_key": prefer(lambda c: has_op(c, "pump") or has_op(c, "grant")),
        },
        {
            "key": "custody",
            "name": "Cold Custody",
            "affinity": "Keys",
            "tagline": "Answer everything, lose nothing - control as the old masters played it.",
            "resources": 17,
            "avatars": 9,
            "spells": 10,
            "devices": 4,
            "avatar_key": wall,
            "spell_key": prefer(lambda c: has_op(c, "invalidate") or has_op(c, "moveTop")),
        },
        {
            "key": "channel",
            "name": "Channel the Grid",
            "affinity": "Bitcoin",
            "tagline": "Resources now, something enormous immediately after - the ramp burst.",
            "resources": 19,
            "avatars": 12,
            "spells": 5,
            "devices": 4,
            "avatar_key": lambda c: (-cost_total(c), -action_of(c) - resilience_of(c), c["id"]),
            "spell_key": prefer(lambda c: has_op(c, "generate")),
        },
        {
            "key": "vise",
            "name": "Tight Buffer",
            "affinity": "Timelock",
            "tagline": "Their cards cost more than yours - denial, the old vise squeeze.",
            "resources": 16,
            "avatars": 11,
            "spells": 9,
            "devices": 4,
            "avatar_key": wall,
            "spell_key": prefer(
                lambda c: has_op(c, "discard") or has_op(c, "decommission") or has_op(c, "bounce")
            ),
        },
        {
            "key": "ledger",
            "name": "The Ledger",
            "affinity": "Keys",
            "tagline": "Card advantage is the only advantage - the deck that answers twice.",
            "resources": 17,
            "avatars": 10,
            "spells": 9,
            "devices": 4,
            "avatar_key": lambda c: (
                -(action_of(c) + resilience_of(c)) + 2 * cost_total(c),
                cost_total(c),
                c["id"],
            ),
            "spell_key": prefer(lambda c: has_op(c, "moveTop") or has_op(c, "reboot")),
        },
    ]


STARTER_META = {
    "Power": ("Power Surge", "Fast rigs, raw watts, quick clashes."),
    "Bitcoin": ("Sound Money", "Patient value that compounds."),
    "Keys": ("Key Custody", "Hold your keys, hold the line."),
    "Signal": ("Open Relay", "Reach everyone, answer everything."),
    "Timelock": ("Patient Circuit", "Slow is smooth, and smooth wins."),
}


def build_precons(cards: list[dict]) -> dict[str, dict]:
    """Every shelf, in a stable order: five Starters, then the Classics."""
    out: dict[str, dict] = {}
    for affinity in AFFINITIES:
        name, tagline = STARTER_META[affinity]
        out[name] = {
            "group": "Starter",
            "affinity": affinity,
            "tagline": tagline,
            "cards": starter(cards, affinity),
        }
    for spec in classics_specs():
        out[spec["name"]] = {
            "group": "Classic",
            "affinity": spec["affinity"],
            "tagline": spec["tagline"],
            "cards": classic(cards, spec),
        }
    for name, precon in out.items():
        if len(precon["cards"]) < 40:
            raise SystemExit(f"{name}: only {len(precon['cards'])} cards - pool too thin")
    return out


def main() -> None:
    cards = load_cards()
    precons = build_precons(cards)
    body = json.dumps(precons, indent=1, ensure_ascii=False)
    exports = (
        'if (typeof module === "object" && module.exports) module.exports = globalThis.E1_PRECONS;'
    )
    OUT.write_text(f"{HEADER}globalThis.E1_PRECONS = {body};\n{exports}\n", encoding="utf-8")
    total = sum(len(p["cards"]) for p in precons.values())
    print(f"wrote {OUT} ({len(precons)} Stacks, {total} cards)")


if __name__ == "__main__":
    main()
